-----
#### Author: NJ Namju Lee / nj.namju@gmail.com  
###### * Linkedin - https://www.linkedin.com/in/nj-namju-lee-926b3252/    * Git - https://github.com/NamjuLee  

###### * Web - http://www.njstudio.co.kr                                  * Lab - http://www.njslab.com/NJSLabCore/  

###### * Video(English) - https://www.youtube.com/c/njnamjulee            * Writing(English) - https://medium.com/@nj-namju  

###### * Video(Korean) - https://www.youtube.com/c/CodeforDesign          * Writing(Korean) - https://brunch.co.kr/@njnamju  
-----

# 4. Models

In [16]:
import pandas as pd
import numpy as np

# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

## 4.1 Import Data for Training Logistic Regression

In [17]:
dfDis = pd.read_csv('data/cooked/google-third-place-Boston_DistanceClosest.csv')
dfDis = dfDis.iloc[:, 1:]

dataSetDis = dfDis.to_numpy()
np.random.seed(222)
np.random.shuffle(dataSetDis)
X_dis = dataSetDis[:,:-1]
y_dis = dataSetDis[:,-1:].flatten()

dfDecay = pd.read_csv('data/cooked/google-third-place-Boston_DecayClosest.csv')
dfDecay = dfDecay.iloc[:, 1:]
print(dfDecay.shape)

dataSetDecay = dfDecay.to_numpy()
np.random.seed(222)
np.random.shuffle(dataSetDecay)
X_decay = dataSetDecay[:,:-1]
y_decay = dataSetDecay[:,-1:].flatten()

(3469, 96)


In [18]:
XTrain_dis, XTest_dis, yTrain_dis, yTest_dis =train_test_split(X_dis, y_dis, test_size=0.2)
std_scale = StandardScaler()
std_scale.fit(XTrain_dis)
XTrainStd_dis = std_scale.transform(XTrain_dis)
XTestStd_dis  = std_scale.transform(XTest_dis)

XTrain_decay, XTest_decay, yTrain_decay, yTest_decay =train_test_split(X_decay, y_decay, test_size=0.2)
std_scale = StandardScaler()
std_scale.fit(XTrain_decay)
XTrainStd_decay = std_scale.transform(XTrain_decay)
XTestStd_decay  = std_scale.transform(XTest_decay)

## 4.2 Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression

lrL2_dis =  LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='none', random_state=2)
lrL2_dis.fit(XTrainStd_dis, yTrain_dis)

print('shape: ', lrL2_dis.coef_.shape)
print('coef:', lrL2_dis.coef_)
print('intercept:', lrL2_dis.intercept_)

/Users/hupbook/miniconda3/envs/nj-urban/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1183: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(


shape:  (91, 95)
coef: [[-1.32411475e+01  7.57703712e-01 -2.59036866e-02 ... -1.56072965e+00
  -2.13278052e-01 -1.44002624e-02]
 [ 3.82441585e-01 -1.71826356e+01  1.15993230e+00 ...  5.65947876e-01
   2.34931714e+00  1.22438197e+00]
 [-3.05695358e-01  7.64177111e-01 -2.19415500e+01 ...  2.66048982e+00
  -4.69749726e-01  1.96430793e-01]
 ...
 [-5.87175850e-01  4.61001643e-01 -2.44034053e+00 ...  1.65491487e+00
   1.67030004e+00  4.55746189e-01]
 [ 1.19336930e+00 -5.21809273e-01  1.71542581e+00 ... -2.25651226e+01
   4.52193229e-01  5.27824957e-01]
 [ 7.35577838e-01  2.06335330e+00  2.65331724e+00 ...  1.60352788e+00
  -2.07277408e+01  1.44722850e+00]]
intercept: [ -1.28184336  -7.95289461   2.63916357  -8.00499193  -7.21750992
   6.50418693  -3.17949266   5.62544234   9.43204453  -5.70024025
  -7.26831324   9.90541219  -7.83384252   1.66383876  -7.04661904
  -6.38231345   8.8890572    4.52650148  -2.38835222  -7.8380407
  -7.54936526  -2.10840798 -11.14215921  -8.08211468   7.61184948
 

/Users/hupbook/miniconda3/envs/nj-urban/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [20]:
lrL2_decay =  LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='none', random_state=2)
lrL2_decay.fit(XTrainStd_decay, yTrain_decay)

print('shape: ', lrL2_decay.coef_.shape)
print('coef:', lrL2_decay.coef_)
print('intercept:', lrL2_decay.intercept_)

/Users/hupbook/miniconda3/envs/nj-urban/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1183: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(


shape:  (92, 95)
coef: [[ 2.94646768e+01 -1.05107797e-01 -2.66165017e-01 ...  1.15630653e+00
  -2.36679952e-01 -3.48038025e-02]
 [-1.82446245e-01  1.70492131e+01 -1.05872455e-01 ... -4.65014160e-01
  -9.39785204e-02  4.14466614e-02]
 [-1.29772508e-01  1.03485634e-04  1.60287995e+01 ... -3.47181228e-01
  -8.17445054e-02  4.78175089e-02]
 ...
 [-4.72705743e-01 -7.94256709e-01 -1.35285680e+00 ...  5.61897958e+01
  -1.24963960e+00 -4.67645837e-01]
 [-1.78887250e-01  3.34717242e-03 -9.56141082e-02 ... -2.47793094e-01
   1.76869885e+01  4.06531299e-02]
 [ 1.17454071e-01  1.25299666e-01  1.14361829e-01 ...  8.59986396e-02
   8.03182088e-02  1.19982127e+00]]
intercept: [-1.12022397 -2.53920037 -2.65727951 -2.14107685 -3.74000614  1.1633107
 -1.52161569  8.63214284  5.17907117 -2.85297379 -3.55268365  3.02466449
 -3.75238647 -1.9657463  -2.00206364  6.39731289  0.91196226 -0.73495297
  7.50136589 -3.711056   -2.87526989  3.45276971  5.878756   -0.14813796
  6.26452644  7.00969624 -1.89196244 -3

/Users/hupbook/miniconda3/envs/nj-urban/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [21]:
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix

pred_logistic_dis = lrL2_dis.predict(XTestStd_dis)
print(pred_logistic_dis)
print(precision_score(yTest_dis, pred_logistic_dis,  average='micro'))

[13. 82. 77. 30.  3. 68. 92. 64. 23. 25. 79. 88. 35. 69. 34. 16. 75. 23.
 44. 92. 68. 80.  2. 66. 25. 14. 80. 48. 48. 82. 41. 42. 48. 25. 17. 22.
 23. 22. 31. 11. 88. 62. 60. 78. 75. 90.  2. 23. 26. 92. 23. 60. 17. 30.
 82.  3. 22.  8. 28. 30. 58. 30. 80. 71. 82. 92. 89. 48.  7. 44. 87. 26.
 15.  9. 50. 83. 58. 15. 33. 21. 78. 31.  8. 18.  7. 16. 80. 92. 24. 18.
 88.  9. 18. 50. 66. 84. 48. 67.  8. 23. 18. 18. 64. 58. 51. 44. 23.  9.
 88. 58. 32. 88. 54. 42. 82. 27. 91.  5. 66. 72. 54. 51. 75. 26. 75. 34.
 74. 69. 33. 17. 33. 58. 35. 23. 23. 22. 32. 54. 88. 13. 18. 44. 30. 82.
 92. 41. 75. 58. 49. 48. 62. 83. 49.  7. 15. 22. 75. 16. 37. 84. 23. 22.
 88. 84. 89. 64. 88. 48. 80. 18. 89. 78.  2. 71. 26. 45. 46. 23. 62. 67.
 80. 54. 44. 33. 90. 51. 42. 92. 88.  5. 17.  8. 45. 15.  5. 42. 82. 33.
 50. 92. 27. 37.  8. 74. 62.  8. 45. 88. 62. 60. 68. 15. 18. 11. 17. 33.
 54. 25.  3. 49. 21. 58.  8. 11. 22. 13. 89. 30. 82. 44. 23. 87.  9. 62.
 83. 71. 55. 26. 82. 16. 16. 18. 44.  0. 17. 91.  8

In [22]:
pred_logistic_decay = lrL2_decay.predict(XTestStd_decay)
print(pred_logistic_decay)
print(precision_score(yTest_decay, pred_logistic_decay,  average='micro'))

[37. 13. 58. 50. 35. 87. 80. 40.  7. 26.  2. 23. 80. 37. 58. 23. 29. 54.
  6. 71. 68. 18. 26. 44. 74. 90. 22. 55. 72. 23. 35. 18. 49. 25.  6. 23.
 62. 88. 48. 54. 89. 91. 30. 44. 34. 42. 51. 42. 30. 50. 62. 24. 18. 88.
 44. 91. 83. 83.  2. 54. 35. 40. 73. 13. 51. 44. 60. 75. 26. 51. 62. 68.
 78. 26. 91. 49. 55. 16. 32. 26. 26. 69. 58. 64. 25. 69.  9. 82. 24. 91.
 78.  7. 60. 78. 68. 42. 48. 54. 15. 73. 48. 80. 86. 23. 69. 23. 89. 51.
 22. 18. 51. 80. 49. 83.  8. 22. 40. 37. 25. 58. 51. 80. 46. 42. 22. 55.
 44. 25. 40. 71. 18. 24. 60. 55. 92. 58. 30. 15. 82. 31. 84. 71.  7. 16.
 45. 91. 25. 58. 11. 24.  8. 71. 92. 16. 88. 88. 67. 71. 11. 22. 73. 16.
 55. 71. 11. 69. 71. 51. 22. 64. 71.  9. 37. 62. 35. 82. 51. 34. 54.  3.
 48. 75. 51. 33. 79. 84. 22. 22. 64. 16.  7. 11. 75. 86. 62. 80. 89. 15.
 86.  2. 86. 55.  5. 82. 22. 35. 72. 25. 22. 23.  7. 17. 25.  4. 22. 13.
 22. 91. 51. 60. 84. 24. 13. 84. 60. 22. 25. 40. 84. 54. 23. 16. 68.  7.
 15. 54.  8. 23. 45. 25. 24. 60.  9.  5. 46. 50. 49

In [23]:
print(lrL2_dis.predict_proba(XTestStd_dis))
print(confusion_matrix(yTest_dis, pred_logistic_dis))

[[4.83497727e-04 1.74092509e-32 8.76157224e-12 ... 3.14094341e-26
  1.27128045e-23 1.05044761e-02]
 [2.79147395e-04 7.44537953e-10 4.39501608e-13 ... 2.43322401e-06
  6.46736880e-04 2.67427419e-17]
 [1.22587635e-03 1.26088734e-15 1.41344449e-16 ... 6.93012852e-06
  2.64041868e-03 8.14101395e-11]
 ...
 [6.11697364e-06 5.15318727e-11 6.77978246e-09 ... 1.11249561e-04
  2.06070078e-04 7.73029349e-21]
 [2.70291339e-02 1.62932600e-11 1.04804674e-10 ... 4.03149744e-02
  6.13075879e-02 3.54743019e-25]
 [5.36662939e-21 1.20717157e-14 6.58115534e-19 ... 3.10156374e-02
  2.21330262e-06 4.86039661e-14]]
[[0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 6 ... 0 0 0]
 ...
 [1 0 0 ... 3 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [24]:
print(lrL2_decay.predict_proba(XTestStd_decay))
print(confusion_matrix(yTest_decay, pred_logistic_decay))

[[2.56706957e-090 8.74152090e-089 4.22812993e-088 ... 1.36073469e-098
  9.83407137e-089 1.70017461e-089]
 [3.40793875e-103 2.50218297e-106 9.49125399e-129 ... 1.10259654e-086
  1.30388602e-106 6.03406179e-107]
 [1.23703521e-097 7.29425187e-096 3.34164307e-094 ... 6.21402352e-104
  6.52261568e-096 2.31102782e-097]
 ...
 [5.18986026e-095 5.45453430e-092 3.35727863e-095 ... 1.24240732e-092
  1.30205658e-091 3.55250232e-087]
 [2.22550464e-082 3.00704270e-083 9.70829167e-083 ... 2.55330483e-090
  6.67935583e-084 4.60314164e-087]
 [1.78827807e-002 1.20852590e-092 1.99020487e-090 ... 6.75717374e-100
  6.38250104e-092 5.07855596e-091]]
[[2 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 9 ... 0 0 0]
 ...
 [0 0 0 ... 9 0 0]
 [0 0 0 ... 0 9 0]
 [0 0 0 ... 0 0 2]]


In [25]:
prob = lrL2_decay.predict_proba(XTestStd_decay)[0]
prob

array([2.56706957e-090, 8.74152090e-089, 4.22812993e-088, 8.21903743e-089,
       5.05884877e-089, 1.73506426e-092, 2.13207067e-092, 1.03102386e-068,
       3.76011663e-094, 2.82275189e-089, 4.20891817e-090, 9.49178277e-066,
       1.70050359e-089, 1.13689262e-089, 5.99965222e-088, 2.96350053e-083,
       6.01719511e-089, 1.52901679e-090, 4.73094739e-053, 1.75251475e-089,
       2.25228981e-089, 5.24763416e-089, 1.50039456e-107, 1.31043858e-089,
       3.84659326e-101, 4.02850778e-111, 8.33992744e-089, 1.70085797e-089,
       1.30915765e-089, 4.30495367e-090, 1.12046619e-089, 3.93604751e-089,
       7.42583774e-087, 2.23212311e-089, 2.48787319e-090, 2.47697474e-089,
       1.00000000e+000, 3.25000666e-089, 1.71357042e-093, 2.28535704e-083,
       5.23465219e-090, 5.09819199e-066, 5.95594792e-104, 2.93071607e-087,
       5.58569550e-089, 1.04815090e-088, 1.67698568e-042, 4.37364078e-090,
       4.93848740e-090, 1.10218872e-094, 1.69979009e-089, 1.69989866e-089,
       2.89665978e-100, 5

## 4.3 SVM

In [26]:
# https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
from sklearn import svm 

lrSVM_dis = svm.SVC(kernel='linear', random_state=2)
lrSVM_dis.fit(XTrainStd_dis, yTrain_dis)

lrSVM_decay = svm.SVC(kernel='linear', random_state=2)
lrSVM_decay.fit(XTrainStd_decay, yTrain_decay)

SVC(kernel='linear', random_state=2)

In [27]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

predSVM_dis = lrSVM_dis.predict(XTestStd_dis)
print(predSVM_dis)
print(accuracy_score(yTest_dis, predSVM_dis))

[93. 82. 27. 58. 87. 51. 91.  0. 23. 25. 27. 45. 17. 50.  7. 42. 75. 23.
 44. 80.  6. 80. 48. 55. 16. 58. 80. 24. 17. 45.  2. 68. 58. 25. 30. 22.
 23. 22. 31. 11. 88. 34. 23. 78. 75. 24. 80. 23. 16.  8. 22. 60. 17. 23.
 42.  3. 22.  8. 85. 30.  7.  0. 30.  8. 82. 91. 68. 23. 82. 18. 87. 54.
 15.  9. 31. 83. 82. 51. 89. 11. 78. 31.  8. 22. 30. 30. 58. 80. 40. 22.
 88. 88. 15. 31. 18. 84. 89. 82.  8. 23. 18. 22. 23. 37. 54. 18. 23.  8.
 51. 51. 32.  7. 54. 42. 15. 27. 91. 25. 55. 72.  8. 88. 88. 50. 75. 35.
 35. 17.  5. 17. 16. 51. 82. 23. 23. 55. 68. 25. 88. 45. 18. 58. 15. 15.
 23. 68. 60. 15. 49. 48. 62. 18. 90. 11. 15. 44. 89. 30.  6. 48. 23. 22.
 88. 68. 88. 64. 88. 83. 80. 22. 58. 16. 82. 88. 26. 60.  0. 23.  2. 67.
 51. 18. 44. 33. 90. 51. 91. 88. 88. 25. 91.  8. 45. 15. 49. 42. 82. 30.
 31. 92.  0. 37. 91. 35. 18. 58. 14. 88. 62. 23. 26. 51. 18. 25. 60. 77.
 22. 25.  3. 49. 32. 58.  8. 30. 55. 91. 89. 30. 82. 18. 23.  8.  9. 48.
 51. 88. 18. 23. 82. 16. 16. 25. 15. 40. 91. 82.  8

In [28]:
predSVM_decay = lrSVM_decay.predict(XTestStd_decay)
print(predSVM_decay)
print(accuracy_score(yTest_decay, predSVM_decay))

[37. 13. 58. 50. 35. 87. 80. 40.  7. 26.  2. 23. 80. 37. 58. 72. 29. 54.
  6. 71. 68.  8. 26. 44. 74. 37. 22. 55. 72. 30. 35. 18. 49. 25.  6. 55.
 62. 40. 44. 54. 89. 51. 30. 44. 34. 42. 88. 42. 30. 50. 62. 24. 18. 88.
 44. 91. 83. 88.  2. 54. 35. 40. 73. 13. 15. 44. 60. 11. 26. 51. 62. 68.
 78. 23. 91. 49.  8. 16. 32. 26. 26. 15. 58. 64. 25. 69.  9. 82. 24. 91.
 78.  7. 60. 78. 68. 42. 48. 54. 15. 73. 48. 80. 86. 23. 69. 23. 89. 35.
 22. 69. 51. 80. 49. 83.  8. 22. 40. 37. 48. 37. 48. 80. 46. 42. 22. 55.
 44. 25. 40. 71. 18. 24. 60. 78. 92. 58. 30. 15. 82. 31. 84. 71.  7. 16.
 45. 91. 25. 58. 11. 24. 71.  6. 92. 16. 23. 88. 67. 71. 11. 22. 73. 16.
 54. 71. 11. 69. 71.  8. 22. 64. 25.  9. 37. 62. 35. 82. 88. 34. 54.  3.
 48. 75. 51. 33. 79. 84. 22. 44. 64. 16.  7. 11. 75. 42. 62. 80. 89. 15.
 86.  2. 86. 55.  5. 82. 22. 35. 72. 25. 22. 23. 23. 17. 25.  4. 22. 13.
 22. 91. 51. 60. 84. 24. 13. 51. 60. 22. 25. 40. 84. 54. 23. 16. 68.  7.
 15. 54.  8. 23. 45. 25. 24. 60.  9.  5. 46. 44. 49

In [29]:
print(confusion_matrix(yTest_dis, predSVM_dis))

[[0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


-----
### References & Useful links

Lee, N. (2021). Understanding and Analyzing the Characteristics of the Third Place in Urban Design: A Methodology for Discrete and Continuous Data in Environmental Design. In: Yuan, P.F., Yao, J., Yan, C., Wang, X., Leach, N. (eds) Proceedings of the 2020 DigitalFUTURES. CDRF 2020. Springer, Singapore. https://doi.org/10.1007/978-981-33-4400-6_11



Oldenburg, R., Brissett, (1982). D.: The third place. Qual. Sociol. 5(4), 265–284



Lee, Namju. (2022). Computational Design, Seoul, Bookk, https://brunch.co.kr/@njnamju/144



Lee, Namju, (2022). Discrete Urban Space and Connectivity, https://nj-namju.medium.com/discrete-urban-space-and-connectivity-492b3dbd0a81



Woo. Junghyun, (2022). Numeric Network Analysis for Pedestrians, https://axuplatform.medium.com/0-numeric-network-analysis-47a2538e636c



Lee, Namju, (2022). Computational Design Thinking for Designers, https://nj-namju.medium.com/computational-design-thinking-for-designers-68224bb07f5c



Lee, Namju. (2016). Third Place Mobility Energy Consumption Per Person, http://www.njstudio.co.kr/main/project/2016_MobilityEnergyConsumptionMITMediaLab 
