-----
#### Author: NJ Namju Lee / nj.namju@gmail.com  
###### * Linkedin - https://www.linkedin.com/in/nj-namju-lee-926b3252/    * Git - https://github.com/NamjuLee  

###### * Web - http://www.njstudio.co.kr                                  * Lab - http://www.njslab.com/NJSLabCore/  

###### * Video(English) - https://www.youtube.com/c/njnamjulee            * Writing(English) - https://medium.com/@nj-namju  

###### * Video(Korean) - https://www.youtube.com/c/CodeforDesign          * Writing(Korean) - https://brunch.co.kr/@njnamju  
-----

# 4. Models

In [1]:
import pandas as pd
import numpy as np

# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

## 4.1 Import Data for Training Logistic Regression

In [2]:
dfDis = pd.read_csv('data/cooked/google-third-place-Boston_DistanceClosest.csv')
dfDis = dfDis.iloc[:, 1:]

dataSetDis = dfDis.to_numpy()
np.random.seed(222)
np.random.shuffle(dataSetDis)
X_dis = dataSetDis[:,:-1]
y_dis = dataSetDis[:,-1:].flatten()

dfDecay = pd.read_csv('data/cooked/google-third-place-Boston_DecayClosest.csv')
dfDecay = dfDecay.iloc[:, 1:]
print(dfDecay.shape)

dataSetDecay = dfDecay.to_numpy()
np.random.seed(222)
np.random.shuffle(dataSetDecay)
X_decay = dataSetDecay[:,:-1]
y_decay = dataSetDecay[:,-1:].flatten()

(6179, 96)


In [3]:
XTrain_dis, XTest_dis, yTrain_dis, yTest_dis =train_test_split(X_dis, y_dis, test_size=0.2)
std_scale = StandardScaler()
std_scale.fit(XTrain_dis)
XTrainStd_dis = std_scale.transform(XTrain_dis)
XTestStd_dis  = std_scale.transform(XTest_dis)

XTrain_decay, XTest_decay, yTrain_decay, yTest_decay =train_test_split(X_decay, y_decay, test_size=0.2)
std_scale = StandardScaler()
std_scale.fit(XTrain_decay)
XTrainStd_decay = std_scale.transform(XTrain_decay)
XTestStd_decay  = std_scale.transform(XTest_decay)

## 4.2 Logistic Regression

In [4]:
from sklearn.linear_model import LogisticRegression

lrL2_dis =  LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='none', random_state=2)
lrL2_dis.fit(XTrainStd_dis, yTrain_dis)

print('shape: ', lrL2_dis.coef_.shape)
print('coef:', lrL2_dis.coef_)
print('intercept:', lrL2_dis.intercept_)

/Users/hupbook/miniconda3/envs/nj-urban/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1183: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(


shape:  (89, 95)
coef: [[ -1.02221502  -2.03776831  -1.82882816 ...  -0.09822708  -0.30007364
   -0.1980249 ]
 [ -0.46818334  -0.36979811 -16.28298677 ...   0.97324127   0.52717808
    0.24651238]
 [  0.89581898   0.35324316  -1.40110815 ...   0.62016896   0.75647729
    0.21324523]
 ...
 [ -0.46567814   0.06271899   1.49604573 ... -21.54784894   0.18846758
    0.51288048]
 [  0.62745112  -0.93331308   1.24672483 ...  -1.76959436  -3.37187889
   -0.16415056]
 [ -0.22062077  -0.22023991   0.45179552 ...   0.42893959  -0.34362415
   -1.45358828]]
intercept: [-6.02094037 -2.12708224 -6.948441   -6.52835826  4.09288617 -4.04775119
 11.82581277  8.53047382 -4.7416135  -7.68690438  6.79596094 -7.10259924
 -4.45675635 -6.10588347 10.59082286  6.40051614 -2.42370064 11.18735068
 -5.84517431 -6.08039448 -6.80919497 11.72901317 10.48257457  1.50069482
  9.64767572  8.87219879 -7.68689054 -7.68669734 -6.619436    8.22489831
 -7.68678356 -2.97816026 -0.02097181  3.97907534 -6.54246989 -0.96981721


/Users/hupbook/miniconda3/envs/nj-urban/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
lrL2_decay =  LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='none', random_state=2)
lrL2_decay.fit(XTrainStd_decay, yTrain_decay)

print('shape: ', lrL2_decay.coef_.shape)
print('coef:', lrL2_decay.coef_)
print('intercept:', lrL2_decay.intercept_)

/Users/hupbook/miniconda3/envs/nj-urban/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1183: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(


shape:  (91, 95)
coef: [[ 4.01598327e+00 -9.30814074e-03  1.20887663e-01 ...  1.44015950e-01
   1.53197217e-02  1.18075421e-01]
 [ 2.54795559e-02  5.43166964e+00  1.12887546e+00 ... -1.76213147e-01
   2.25699769e-02  1.10833829e-01]
 [ 6.97347259e-02 -5.36604742e-01  8.60344801e+00 ... -4.11809857e-02
   9.99292632e-02  9.74161717e-02]
 ...
 [ 5.67366712e-01 -5.10925540e-01 -8.65319446e-01 ...  1.32727636e-01
  -5.51194526e-01 -2.64306228e-01]
 [ 2.88963089e-01 -5.88351999e-01 -6.20953978e-01 ...  3.64894511e+01
  -1.23335985e-01 -1.97991809e-01]
 [-5.19375402e-02 -5.27364190e-02 -7.15740263e-03 ... -1.11340607e-01
   1.17019203e+01  8.24242945e-02]]
intercept: [-2.66436933 -2.51738583 -2.24465361 -2.40985781 -2.60854772 -0.32083932
 -0.82529366  7.00904508  3.14694613 -2.41896014 -2.66211361  1.40026597
 -2.67371891 -0.83360117 -2.53803887  7.3411348   0.82678277 -1.71431796
  6.04036207 -2.55213983 -2.49471594 -2.70710084  7.78931524  8.93449458
 -0.72577883  5.6381056   5.97146392 -

/Users/hupbook/miniconda3/envs/nj-urban/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [6]:
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix

pred_logistic_dis = lrL2_dis.predict(XTestStd_dis)
print(pred_logistic_dis)
print(precision_score(yTest_dis, pred_logistic_dis,  average='micro'))

[69.  7. 68. ... 22. 16. 44.]
0.5226537216828478


In [7]:
pred_logistic_decay = lrL2_decay.predict(XTestStd_decay)
print(pred_logistic_decay)
print(precision_score(yTest_decay, pred_logistic_decay,  average='micro'))

[50. 18.  9. ... 62. 48. 24.]
0.7815533980582524


In [8]:
print(lrL2_dis.predict_proba(XTestStd_dis))
print(confusion_matrix(yTest_dis, pred_logistic_dis))

[[1.02167807e-02 4.00444458e-06 7.39524044e-20 ... 1.51716793e-05
  1.60234258e-20 2.26732850e-17]
 [9.64166591e-05 4.47215838e-10 4.80686243e-15 ... 1.28179650e-04
  3.50811245e-04 1.01036822e-14]
 [1.04156636e-03 1.81188297e-06 2.70137723e-14 ... 2.65307219e-08
  1.01742774e-03 1.54798754e-12]
 ...
 [2.94533440e-15 3.06449092e-10 2.93952370e-06 ... 1.64174256e-14
  2.30729029e-11 2.29234880e-17]
 [1.33004875e-14 1.43296557e-08 5.01925917e-19 ... 3.15932096e-07
  2.89060981e-16 4.42474550e-15]
 [3.79997478e-23 2.38224809e-18 7.69193772e-20 ... 1.37444117e-03
  1.20528457e-23 3.77788049e-20]]
[[ 0  0  0 ...  0  0  1]
 [ 0  6  0 ...  0  0  0]
 [ 0  0  1 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0 18  0]
 [ 0  0  0 ...  0  0 13]]


In [9]:
print(lrL2_decay.predict_proba(XTestStd_decay))
print(confusion_matrix(yTest_decay, pred_logistic_decay))

[[3.69550403e-61 9.65184472e-62 4.65430339e-62 ... 8.18108237e-66
  3.31066906e-66 1.71656845e-61]
 [1.27075656e-63 6.07483607e-64 5.16956571e-63 ... 7.70078608e-70
  1.15508935e-69 6.30801834e-64]
 [1.54147482e-59 2.18315139e-59 1.21639168e-59 ... 1.58090363e-62
  5.63573513e-62 1.97326489e-60]
 ...
 [2.66399406e-55 1.23541579e-54 1.44314936e-55 ... 1.35120803e-58
  2.93091514e-56 1.69128320e-53]
 [3.81343864e-55 1.23288167e-53 7.84175305e-44 ... 1.96836880e-52
  1.19450708e-46 2.33974300e-56]
 [6.91186784e-60 4.27896988e-61 3.34506926e-61 ... 2.82935858e-66
  2.15141832e-37 3.94748266e-64]]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 16 ...  0  0  0]
 ...
 [ 0  0  0 ... 21  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  0 ...  0  0  0]]


In [10]:
prob = lrL2_decay.predict_proba(XTestStd_decay)[0]
prob

array([3.69550403e-61, 9.65184472e-62, 4.65430339e-62, 2.15229236e-61,
       2.03687797e-61, 6.43569065e-62, 6.34266565e-60, 6.89932423e-59,
       3.47471074e-23, 4.96444478e-59, 2.16715557e-61, 5.84774066e-61,
       3.93346253e-61, 1.13999631e-61, 4.62356270e-61, 2.08521108e-63,
       3.12074391e-60, 2.11123555e-59, 7.90152121e-70, 3.96075659e-61,
       7.10278537e-59, 2.21095711e-61, 6.11189077e-45, 9.83334537e-64,
       1.51333651e-57, 5.65594054e-62, 5.67805899e-46, 2.16703541e-61,
       2.16707269e-61, 5.30179382e-60, 1.95617277e-69, 2.16701152e-61,
       2.16752909e-61, 1.59704456e-60, 1.65674837e-60, 6.70296795e-61,
       1.21696702e-60, 3.15102969e-62, 1.65040595e-61, 2.16685480e-61,
       3.68874284e-60, 2.16707329e-61, 1.31389467e-63, 5.86121166e-61,
       1.23389918e-50, 3.01701995e-60, 2.12241812e-61, 3.70655505e-61,
       1.25563752e-66, 1.09384254e-59, 1.00000000e+00, 1.26247439e-67,
       2.16704190e-61, 1.65736235e-68, 1.66637809e-67, 3.91153865e-61,
      

## 4.3 SVM

In [11]:
# https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
from sklearn import svm 

lrSVM_dis = svm.SVC(kernel='linear', random_state=2)
lrSVM_dis.fit(XTrainStd_dis, yTrain_dis)

lrSVM_decay = svm.SVC(kernel='linear', random_state=2)
lrSVM_decay.fit(XTrainStd_decay, yTrain_decay)

SVC(kernel='linear', random_state=2)

In [12]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

predSVM_dis = lrSVM_dis.predict(XTestStd_dis)
print(predSVM_dis)
print(accuracy_score(yTest_dis, predSVM_dis))

[ 5.  7. 68. ... 22. 22. 44.]
0.25


In [13]:
predSVM_decay = lrSVM_decay.predict(XTestStd_decay)
print(predSVM_decay)
print(accuracy_score(yTest_decay, predSVM_decay))

[50. 18.  9. ... 62. 48. 24.]
0.6949838187702265


In [14]:
print(confusion_matrix(yTest_dis, predSVM_dis))

[[0 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 4 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


-----
### References & Useful links

Lee, N. (2021). Understanding and Analyzing the Characteristics of the Third Place in Urban Design: A Methodology for Discrete and Continuous Data in Environmental Design. In: Yuan, P.F., Yao, J., Yan, C., Wang, X., Leach, N. (eds) Proceedings of the 2020 DigitalFUTURES. CDRF 2020. Springer, Singapore. https://doi.org/10.1007/978-981-33-4400-6_11



Oldenburg, R., Brissett, (1982). D.: The third place. Qual. Sociol. 5(4), 265–284



Lee, Namju. (2022). Computational Design, Seoul, Bookk, https://brunch.co.kr/@njnamju/144



Lee, Namju, (2022). Discrete Urban Space and Connectivity, https://nj-namju.medium.com/discrete-urban-space-and-connectivity-492b3dbd0a81



Woo. Junghyun, (2022). Numeric Network Analysis for Pedestrians, https://axuplatform.medium.com/0-numeric-network-analysis-47a2538e636c



Lee, Namju, (2022). Computational Design Thinking for Designers, https://nj-namju.medium.com/computational-design-thinking-for-designers-68224bb07f5c



Lee, Namju. (2016). Third Place Mobility Energy Consumption Per Person, http://www.njstudio.co.kr/main/project/2016_MobilityEnergyConsumptionMITMediaLab 
